// Playwright E2E configuration.
// Runs against a local Next.js dev server on port 3001.
// All external HTTP (Stripe, GHL, SunBiz, Resend) is intercepted by MSW via
// instrumentation.ts — no real API calls are made.

import { defineConfig, devices } from '@playwright/test'
import { resolve } from 'path'
import * as dotenv from 'dotenv'
import * as fs from 'fs'

// Load .env.e2e so playwright.config has access to the same env vars
// that are forwarded to the Next.js webServer process.
dotenv.config({ path: resolve(__dirname, '.env.e2e') })

// Write .env.development.local BEFORE the webServer starts.
// Next.js loads .env.development.local with highest priority among env files,
// ensuring compass_test overrides .env.local (compass_db) during E2E.
// globalSetup runs AFTER the webServer starts, so this must happen here.
const devLocalPath = resolve(__dirname, '.env.development.local')
const fontsMockPath = resolve(__dirname, 'tests/e2e/support/google-fonts-mock.js')
fs.writeFileSync(
  devLocalPath,
  [
    '# AUTO-GENERATED by playwright.config.ts — do not commit',
    `DATABASE_URL=${process.env.DATABASE_URL}`,
    `NEXTAUTH_URL=${process.env.NEXTAUTH_URL}`,
    `NEXTAUTH_SECRET=${process.env.NEXTAUTH_SECRET}`,
    `COMPASS_TENANT_ID=${process.env.COMPASS_TENANT_ID}`,
    `ENABLE_MSW=true`,
    // Bypass next/font/google network requests — uses mock CSS so no real font downloads
    `NEXT_FONT_GOOGLE_MOCKED_RESPONSES=${fontsMockPath}`,
    '',
  ].join('\n'),
  'utf8'
)

export default defineConfig({
  testDir: './tests/e2e',
  // Allow each E2E test up to 90 seconds (auth + page loads + DB round-trips)
  timeout: 90_000,
  expect: { timeout: 10_000 },

  // Run test files serially — no parallel browser contexts sharing the same DB tenant
  fullyParallel: false,
  workers: 1,

  reporter: [['list'], ['html', { outputFolder: 'playwright-report', open: 'never' }]],

  use: {
    baseURL: 'http://localhost:3001',
    // Keep a HAR trace on failure for debugging
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    // All requests go to the local Next.js server
    extraHTTPHeaders: {
      'x-e2e-test': 'true',
    },
  },

  // Run only on Chromium to keep CI lean
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  // Global setup/teardown: seed DB before tests, clean after
  globalSetup: './tests/e2e/support/global-setup.ts',
  globalTeardown: './tests/e2e/support/global-teardown.ts',

  // Start Next.js dev server on port 3001 with E2E env vars.
  // Playwright merges these ON TOP of process.env so they override any value
  // already in the parent shell. Next.js dotenv (which loads .env.local) will
  // not override values already present in the child process.env.
  webServer: {
    command: 'node node_modules/next/dist/bin/next dev -p 3001',
    url: 'http://localhost:3001',
    timeout: 120_000,
    reuseExistingServer: false,
    env: {
      DATABASE_URL: 'postgresql://compass:compass@localhost:5433/compass_test',
      NEXTAUTH_URL: 'http://localhost:3001',
      NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET ?? 'e2e-test-secret-compass-local-only',
      COMPASS_TENANT_ID: 'tenant_e2e_compass_01',
      ENABLE_MSW: 'true',
      CRON_SECRET: process.env.CRON_SECRET ?? 'e2e-cron-secret',
      ENCRYPTION_KEY: process.env.ENCRYPTION_KEY ?? '0'.repeat(64),
      NEXT_PUBLIC_APP_URL: 'http://localhost:3001',
      STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ?? 'sk_test_e2e_fake',
      STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET ?? 'whsec_e2etestkey32characterslongpadded',
      GHL_API_KEY: process.env.GHL_API_KEY ?? 'e2e_fake_ghl_api_key',
      GHL_LOCATION_ID: process.env.GHL_LOCATION_ID ?? 'loc_e2e_test_123',
      GHL_PIPELINE_ID: process.env.GHL_PIPELINE_ID ?? 'pipeline_e2e_test_456',
      GHL_STAGE_MAP: process.env.GHL_STAGE_MAP ?? '{"INTAKE":"stage_e2e_1","DATA_QC":"stage_e2e_2","READY_TO_FILE":"stage_e2e_3","FILED":"stage_e2e_4","COMPLETED":"stage_e2e_5"}',
      GHL_WEBHOOK_SECRET: process.env.GHL_WEBHOOK_SECRET ?? 'e2e_ghl_webhook_signing_key_local',
      // Bypass next/font/google network requests during page compilation
      NEXT_FONT_GOOGLE_MOCKED_RESPONSES: fontsMockPath,
    },
    stdout: 'pipe',
    stderr: 'pipe',
  },
})
